import { DEFAULT_FILES } from "@/lib/constants";
import { createId, nowIso } from "@/lib/ids";
import type { AgentEvent, BuilderMode, GenerateResponse, SandpackFiles } from "@/lib/schemas";

export function createFallbackGeneration(prompt: string, mode: BuilderMode, variant = 0): GenerateResponse {
  const projectName = titleFromPrompt(prompt, variant);
  const accent = variant === 1 ? "#0f8f72" : "#334bfa";
  const warm = variant === 1 ? "#fff7e2" : "#eef3ff";
  const resumePrompt = isResumePrompt(prompt);
  const files = resumePrompt
    ? createResumeEvaluatorFiles(projectName, prompt, mode, accent, warm)
    : createGenericFiles(projectName, prompt, mode, accent, warm);
  const summary = resumePrompt
    ? "真实模型暂不可用或返回不可解析内容，已用本地兜底生成一个可运行的 AI 简历评估工具。"
    : "真实模型暂不可用或返回不可解析内容，已用本地规则生成一个可运行 React 原型，便于完整演示工作流。";

  const base: GenerateResponse = {
    projectName,
    mode,
    model: "local-fallback",
    usedFallback: true,
    agentEvents: createAgentEvents(mode, prompt, true),
    files,
    summary,
    checks: ["生成了必要 Sandpack 文件", "限制依赖为白名单", "可继续通过修复接口迭代"],
  };

  if (mode === "race") {
    const other = createFallbackGeneration(prompt, "team", 1);
    const labels = resumePrompt
      ? ["方案 A：HR 评分工作台", "方案 B：候选人建议面板"]
      : ["方案 A：高转化首页", "方案 B：运营看板风格"];

    return {
      ...base,
      candidates: [
        {
          id: createId("candidate"),
          label: labels[0],
          model: "local-fallback-a",
          summary: base.summary,
          files: base.files,
          checks: base.checks,
        },
        {
          id: createId("candidate"),
          label: labels[1],
          model: "local-fallback-b",
          summary: other.summary,
          files: other.files,
          checks: other.checks,
        },
      ],
    };
  }

  return base;
}

function createGenericFiles(
  projectName: string,
  prompt: string,
  mode: BuilderMode,
  accent: string,
  warm: string,
): SandpackFiles {
  return {
    ...DEFAULT_FILES,
    "/src/App.tsx": {
      active: true,
      code: `import { ArrowRight, CheckCircle2, PanelsTopLeft, Rocket, Sparkles } from "lucide-react";

const projectName = ${stringLiteral(projectName)};
const originalPrompt = ${stringLiteral(prompt)};

const features = [
  "围绕真实需求生成信息架构",
  "可直接预览与迭代的 React 页面",
  "保留发布、分享和修复的后续空间"
];

export default function App() {
  return (
    <main className="app">
      <nav>
        <strong>{projectName}</strong>
        <span>AI generated prototype</span>
      </nav>
      <section className="hero">
        <div className="eyebrow"><Sparkles size={16} /> Generated by ${modeLabel(mode)}</div>
        <h1>{projectName}</h1>
        <p>{originalPrompt}</p>
        <div className="actions">
          <button>打开预览 <ArrowRight size={18} /></button>
          <button className="secondary"><PanelsTopLeft size={18} /> 查看模块</button>
        </div>
      </section>
      <section className="cards">
        {features.map((feature) => (
          <article key={feature}>
            <CheckCircle2 />
            <h2>{feature}</h2>
            <p>这是由智能体根据你的提示词生成的可运行模块，可继续通过右侧会话修改。</p>
          </article>
        ))}
      </section>
      <footer>
        <Rocket size={18} />
        <span>Ready to publish from App Viewer</span>
      </footer>
    </main>
  );
}
`,
    },
    "/src/styles.css": {
      code: `* { box-sizing: border-box; }
body {
  margin: 0;
  min-height: 100vh;
  color: #14161b;
  background: ${warm};
  font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
}
.app {
  min-height: 100vh;
  padding: 28px clamp(18px, 5vw, 72px) 42px;
  background:
    linear-gradient(135deg, ${accent}22, transparent 34%),
    linear-gradient(315deg, #f4b84a2b, transparent 32%),
    ${warm};
}
nav {
  display: flex;
  justify-content: space-between;
  gap: 16px;
  align-items: center;
  padding: 12px 0;
}
nav strong { font-size: 20px; }
nav span { color: #626773; }
.hero {
  max-width: 900px;
  padding: 80px 0 48px;
}
.eyebrow {
  display: inline-flex;
  align-items: center;
  gap: 8px;
  border: 1px solid #d9d5c8;
  border-radius: 999px;
  background: rgba(255,255,255,.66);
  padding: 8px 12px;
  font-weight: 800;
}
h1 {
  margin: 22px 0 18px;
  font-size: clamp(42px, 8vw, 88px);
  line-height: .94;
  letter-spacing: 0;
}
.hero p {
  max-width: 720px;
  font-size: 18px;
  line-height: 1.7;
  color: #525864;
}
.actions {
  display: flex;
  flex-wrap: wrap;
  gap: 12px;
  margin-top: 28px;
}
button {
  display: inline-flex;
  align-items: center;
  gap: 8px;
  border: 0;
  border-radius: 8px;
  padding: 13px 17px;
  color: white;
  background: ${accent};
  font-weight: 900;
  box-shadow: 0 10px 24px ${accent}33;
}
button.secondary {
  color: #15171c;
  background: rgba(255,255,255,.8);
  border: 1px solid #ddd7c8;
  box-shadow: none;
}
.cards {
  display: grid;
  grid-template-columns: repeat(3, minmax(0, 1fr));
  gap: 16px;
}
article {
  min-height: 210px;
  padding: 24px;
  border: 1px solid #ded9ca;
  border-radius: 8px;
  background: rgba(255,255,255,.72);
}
article svg { color: ${accent}; }
article h2 { margin: 18px 0 10px; font-size: 20px; }
article p { margin: 0; line-height: 1.65; color: #626773; }
footer {
  display: flex;
  align-items: center;
  gap: 8px;
  margin-top: 28px;
  color: #525864;
  font-weight: 700;
}
@media (max-width: 820px) {
  nav { align-items: flex-start; flex-direction: column; }
  .hero { padding-top: 48px; }
  .cards { grid-template-columns: 1fr; }
}
`,
    },
  };
}

function createResumeEvaluatorFiles(
  projectName: string,
  prompt: string,
  mode: BuilderMode,
  accent: string,
  warm: string,
): SandpackFiles {
  return {
    ...DEFAULT_FILES,
    "/src/App.tsx": {
      active: true,
      code: `import { useMemo, useState, type ChangeEvent } from "react";
import { AlertCircle, CheckCircle2, FileText, Gauge, Lightbulb, Sparkles, Upload } from "lucide-react";

const projectName = ${stringLiteral(projectName)};
const originalPrompt = ${stringLiteral(prompt)};

const sampleResume = "候选人：李明\\n目标岗位：前端工程师\\n经验：4 年 React / TypeScript 项目经验，负责 SaaS 数据看板、组件库和性能优化。\\n亮点：主导简历解析工具落地，LCP 优化 32%，维护 Jest / Playwright 自动化测试。\\n项目：搭建低代码页面生成器，与后端协作完成权限、发布和审计能力。";

const keywordGroups = [
  { label: "岗位匹配", keywords: ["react", "typescript", "前端", "ai", "简历", "评估", "产品", "项目"] },
  { label: "能力证据", keywords: ["主导", "负责", "落地", "优化", "增长", "指标", "测试", "上线"] },
  { label: "表达清晰度", keywords: ["目标", "亮点", "项目", "结果", "数据", "协作", "架构", "用户"] }
];

function clamp(value: number) {
  return Math.max(0, Math.min(100, value));
}

function scoreGroup(text: string, keywords: string[], base: number) {
  const lower = text.toLowerCase();
  const hits = keywords.filter((keyword) => lower.includes(keyword.toLowerCase())).length;
  const density = Math.min(text.length / 900, 1) * 18;
  return clamp(Math.round(base + hits * 8 + density));
}

function analyze(text: string) {
  const content = text.trim();
  const lengthBoost = clamp(Math.round(content.length / 18));
  const scores = keywordGroups.map((group, index) => ({
    label: group.label,
    score: scoreGroup(content, group.keywords, 48 + index * 3)
  }));
  const total = clamp(Math.round(scores.reduce((sum, item) => sum + item.score, 0) / scores.length + lengthBoost * 0.16));
  const suggestions = [
    scores[0].score < 78 ? "补充目标岗位关键词，让经历和岗位要求形成直接对应。" : "岗位关键词覆盖较好，可以继续突出业务场景。",
    scores[1].score < 78 ? "每段经历增加可量化结果，例如转化率、效率、成本或稳定性指标。" : "能力证据比较充分，建议保留最有代表性的 2-3 个成果。",
    scores[2].score < 78 ? "把经历改写成“动作 + 方法 + 结果”的结构，减少泛泛描述。" : "表达结构清楚，可以把摘要区再压缩成更强的开场。"
  ];

  return { total, scores, suggestions, ready: content.length > 40 };
}

export default function App() {
  const [resumeText, setResumeText] = useState(sampleResume);
  const [fileName, setFileName] = useState("示例简历.txt");
  const [submitted, setSubmitted] = useState(false);
  const result = useMemo(() => analyze(resumeText), [resumeText]);

  function handleFile(event: ChangeEvent<HTMLInputElement>) {
    const file = event.target.files?.[0];
    if (!file) return;
    setFileName(file.name);
    void file.text()
      .then((content) => {
        setResumeText(content.slice(0, 12000));
        setSubmitted(false);
      })
      .catch(() => {
        setResumeText("当前文件格式无法直接读取，请将简历正文粘贴到文本框中。");
        setSubmitted(false);
      });
  }

  return (
    <main className="app-shell">
      <header className="topbar">
        <div>
          <div className="badge"><Sparkles size={16} /> Generated by ${modeLabel(mode)}</div>
          <h1>{projectName}</h1>
          <p>{originalPrompt}</p>
        </div>
        <div className="score-card">
          <Gauge size={26} />
          <strong>{submitted && result.ready ? result.total : "--"}</strong>
          <span>综合评分</span>
        </div>
      </header>

      <section className="workspace">
        <div className="panel upload-panel">
          <div className="panel-title"><FileText size={20} /> 上传与输入</div>
          <label className="upload-card" htmlFor="resume-file">
            <Upload size={28} />
            <strong>{fileName || "上传简历文件"}</strong>
            <span>支持文本类文件；PDF / Word 可先复制正文到下方</span>
          </label>
          <input id="resume-file" type="file" accept=".txt,.md,.pdf,.doc,.docx" onChange={handleFile} />
          <textarea
            value={resumeText}
            onChange={(event) => {
              setResumeText(event.target.value);
              setSubmitted(false);
            }}
            placeholder="粘贴简历正文，包含目标岗位、项目经历、技能和量化成果。"
          />
          <button type="button" onClick={() => setSubmitted(true)}>
            <Sparkles size={18} /> 开始评估
          </button>
        </div>

        <div className="panel">
          <div className="panel-title"><Gauge size={20} /> 评分维度</div>
          <div className="meter-list">
            {result.scores.map((item) => (
              <div className="meter" key={item.label}>
                <div className="meter-head">
                  <span>{item.label}</span>
                  <strong>{submitted && result.ready ? item.score : "--"}</strong>
                </div>
                <div className="bar"><span style={{ width: submitted && result.ready ? item.score + "%" : "0%" }} /></div>
              </div>
            ))}
          </div>
          {!result.ready && (
            <div className="notice"><AlertCircle size={18} /> 简历内容太短，建议至少输入 40 个字符。</div>
          )}
        </div>

        <div className="panel advice-panel">
          <div className="panel-title"><Lightbulb size={20} /> 优化建议</div>
          {submitted && result.ready ? (
            result.suggestions.map((suggestion) => (
              <article key={suggestion}>
                <CheckCircle2 size={18} />
                <span>{suggestion}</span>
              </article>
            ))
          ) : (
            <div className="empty-state">上传或粘贴简历后点击“开始评估”，这里会生成可执行的修改建议。</div>
          )}
        </div>
      </section>
    </main>
  );
}
`,
    },
    "/src/styles.css": {
      code: `* { box-sizing: border-box; }
body {
  margin: 0;
  min-height: 100vh;
  color: #14161b;
  background: ${warm};
  font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
}
.app-shell {
  min-height: 100vh;
  padding: 28px clamp(18px, 4vw, 54px) 36px;
  background:
    linear-gradient(135deg, ${accent}20, transparent 36%),
    linear-gradient(315deg, #10a37f1f, transparent 32%),
    ${warm};
}
.topbar {
  display: grid;
  grid-template-columns: minmax(0, 1fr) 180px;
  gap: 18px;
  align-items: end;
  margin-bottom: 20px;
}
.badge {
  display: inline-flex;
  align-items: center;
  gap: 8px;
  border: 1px solid #d8dce8;
  border-radius: 999px;
  background: rgba(255,255,255,.72);
  padding: 8px 12px;
  font-weight: 800;
}
h1 {
  margin: 18px 0 10px;
  max-width: 780px;
  font-size: clamp(34px, 5vw, 64px);
  line-height: 1;
  letter-spacing: 0;
}
p {
  max-width: 760px;
  margin: 0;
  color: #5b6170;
  line-height: 1.7;
}
.score-card {
  min-height: 150px;
  border: 1px solid #dce0eb;
  border-radius: 8px;
  background: rgba(255,255,255,.82);
  display: grid;
  place-items: center;
  padding: 18px;
  text-align: center;
}
.score-card svg { color: ${accent}; }
.score-card strong { display: block; font-size: 52px; line-height: .9; }
.score-card span { color: #697081; font-weight: 800; }
.workspace {
  display: grid;
  grid-template-columns: minmax(280px, 1.2fr) minmax(240px, .85fr) minmax(240px, .9fr);
  gap: 16px;
}
.panel {
  min-height: 430px;
  border: 1px solid #dce0eb;
  border-radius: 8px;
  background: rgba(255,255,255,.82);
  padding: 18px;
}
.panel-title {
  display: flex;
  align-items: center;
  gap: 8px;
  margin-bottom: 14px;
  font-size: 18px;
  font-weight: 900;
}
.panel-title svg { color: ${accent}; }
.upload-card {
  display: grid;
  gap: 7px;
  place-items: center;
  min-height: 124px;
  margin-bottom: 12px;
  border: 1px dashed ${accent};
  border-radius: 8px;
  background: ${accent}0f;
  color: #242833;
  text-align: center;
  cursor: pointer;
}
.upload-card span { color: #6b7280; font-size: 13px; }
input[type="file"] { display: none; }
textarea {
  width: 100%;
  min-height: 190px;
  resize: vertical;
  border: 1px solid #dce0eb;
  border-radius: 8px;
  padding: 14px;
  color: #20242d;
  background: #fbfcff;
  outline: none;
  line-height: 1.65;
}
textarea:focus { border-color: ${accent}; box-shadow: 0 0 0 3px ${accent}1d; }
button {
  width: 100%;
  height: 46px;
  margin-top: 12px;
  border: 0;
  border-radius: 8px;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: 8px;
  color: white;
  background: ${accent};
  font-weight: 900;
  box-shadow: 0 12px 26px ${accent}33;
}
.meter-list { display: grid; gap: 18px; margin-top: 12px; }
.meter-head {
  display: flex;
  justify-content: space-between;
  margin-bottom: 8px;
  font-weight: 900;
}
.bar {
  height: 12px;
  overflow: hidden;
  border-radius: 999px;
  background: #edf0f6;
}
.bar span {
  display: block;
  height: 100%;
  border-radius: inherit;
  background: linear-gradient(90deg, ${accent}, #0f8f72);
  transition: width .35s ease;
}
.notice {
  display: flex;
  align-items: center;
  gap: 8px;
  margin-top: 22px;
  border: 1px solid #f0d19c;
  border-radius: 8px;
  background: #fff8e9;
  padding: 12px;
  color: #7c520f;
  font-weight: 800;
}
.advice-panel { display: flex; flex-direction: column; gap: 12px; }
.advice-panel article {
  display: flex;
  gap: 10px;
  border: 1px solid #dce0eb;
  border-radius: 8px;
  background: #fbfcff;
  padding: 13px;
  line-height: 1.55;
}
.advice-panel article svg { flex: 0 0 auto; color: #0f8f72; margin-top: 2px; }
.empty-state {
  min-height: 210px;
  display: grid;
  place-items: center;
  border: 1px dashed #dce0eb;
  border-radius: 8px;
  padding: 18px;
  color: #737b8c;
  line-height: 1.7;
  text-align: center;
}
@media (max-width: 980px) {
  .topbar,
  .workspace { grid-template-columns: 1fr; }
  .score-card { min-height: 120px; }
}
`,
    },
  }
}

export function createRepairFallback(files: SandpackFiles, issue: string) {
  const fixedFiles = {
    ...files,
    "/src/App.tsx": {
      ...(files["/src/App.tsx"] ?? DEFAULT_FILES["/src/App.tsx"]),
      active: true,
      code: `${files["/src/App.tsx"]?.code ?? DEFAULT_FILES["/src/App.tsx"].code}

// Fix note: ${issue.replace(/\*\//g, "")}
`,
    },
  };

  return {
    files: fixedFiles,
    fixSummary: "本地修复兜底已记录问题说明；配置可用模型密钥后会由 Alex 智能体重写相关代码。",
    agentEvents: [
      event("System", "Issue Report", "收到错误报告", issue, "done"),
      event("Alex", "Software Engineer", "应用兜底修复", "已保留当前可运行文件并追加修复说明。", "done"),
    ],
    usedFallback: true,
  };
}

export function createAgentEvents(mode: BuilderMode, prompt: string, fallback = false): AgentEvent[] {
  const actors =
    mode === "engineer"
      ? [["Alex", "Software Engineer", "实现原型"]]
      : [
          ["Mike", "Team Leader", "拆解任务"],
          ["Emma", "Product Manager", "梳理 PRD"],
          ["Bob", "System Architect", "设计结构"],
          ["Alex", "Software Engineer", "生成代码"],
          ["Sarah", "SEO Specialist", "优化文案"],
        ];

  return actors.map(([agent, role, title], index) =>
    event(
      agent as AgentEvent["agent"],
      role,
      title,
      index === 0
        ? `围绕“${prompt.slice(0, 80)}”启动构建${fallback ? "，当前使用本地兜底。" : "。"}`
        : "已完成该阶段并交付给下一位智能体。",
      "done",
    ),
  );
}

function event(agent: AgentEvent["agent"], role: string, title: string, detail: string, status: AgentEvent["status"]) {
  return {
    id: createId("event"),
    agent,
    role,
    title,
    detail,
    status,
    createdAt: nowIso(),
  };
}

function titleFromPrompt(prompt: string, variant: number) {
  const cleaned = prompt
    .replace(/[^\p{L}\p{N}\s-]/gu, "")
    .split(/\s+/)
    .filter(Boolean)
    .slice(0, 6)
    .join(" ");
  return cleaned ? `${cleaned}${variant ? " Lab" : ""}` : "AI Generated App";
}

function modeLabel(mode: BuilderMode) {
  if (mode === "engineer") return "Engineer Mode";
  if (mode === "race") return "Race Mode";
  return "Team Mode";
}

function isResumePrompt(prompt: string) {
  return /简历|履历|求职|候选人|resume|cv|评分|评估|建议/i.test(prompt);
}

function stringLiteral(value: string) {
  return JSON.stringify(value);
}
